#ifndef NXTETRIS_GAME_ENUMS_GAME_EVENT_H_
#define NXTETRIS_GAME_ENUMS_GAME_EVENT_H_

typedef enum {
    GAME_EVENT_SET_X,
    GAME_EVENT_DROP,
    GAME_EVENT_ROT_CL,
    GAME_EVENT_ROT_CC
} GameEvent;

#endif /* NXTETRIS_GAME_ENUMS_GAME_EVENT_H_ */
