#ifndef NXTETRIS_GAME_ENUMS_GAME_STATE_H_
#define NXTETRIS_GAME_ENUMS_GAME_STATE_H_

typedef enum {
    GAME_STATE_PLACING,
    GAME_STATE_FALLING,
    GAME_STATE_PLACED,
    GAME_STATE_FINISHED
} GameState;

#endif /* NXTETRIS_GAME_ENUMS_GAME_STATE_H_ */
