#ifndef NXTETRIS_GAME_ENUMS_PLACEMENT_STATE_H_
#define NXTETRIS_GAME_ENUMS_PLACEMENT_STATE_H_

typedef enum {
    PLACEMENT_STATE_PLACING,
    PLACEMENT_STATE_FALLING,
    PLACEMENT_STATE_PLACED
} PlacementState;

#endif /* NXTETRIS_GAME_ENUMS_PLACEMENT_STATE_H_ */
