#ifndef NXTETRIS_ENGINE_ENUMS_VERTICAL_ALIGNMENT_H_
#define NXTETRIS_ENGINE_ENUMS_VERTICAL_ALIGNMENT_H_

typedef enum {
    VERTICAL_ALIGNMENT_LEFT,
    VERTICAL_ALIGNMENT_CENTER,
    VERTICAL_ALIGNMENT_RIGHT
} VerticalAlignment;

#endif /* NXTETRIS_ENGINE_ENUMS_VERTICAL_ALIGNMENT_H_ */
