#ifndef NXTETRIS_SRC_ENGINE_ENUMS_VERTICAL_ALIGNMENT_H_
#define NXTETRIS_SRC_ENGINE_ENUMS_VERTICAL_ALIGNMENT_H_

/**
 * Generic vertical (x-axis) alignment.
 */
typedef enum {
	VERTICAL_ALIGNMENT_LEFT,
	VERTICAL_ALIGNMENT_CENTER,
	VERTICAL_ALIGNMENT_RIGHT
} VerticalAlignment;

#endif
